
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: spring-blog
    description: Rasoluti Spring Framework.
    author: Raquel
    version: '@project.version@'
spring:
  profiles:
    active: dev